-- FormCoach Database Initialization
-- Run this after creating the database: CREATE DATABASE form_coach DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 1. User table
CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
    password VARCHAR(255) NOT NULL COMMENT 'BCrypt加密密码',
    nickname VARCHAR(50) DEFAULT '' COMMENT '昵称',
    avatar VARCHAR(255) DEFAULT '' COMMENT '头像URL',
    height DECIMAL(5,1) DEFAULT NULL COMMENT '身高(cm)',
    weight DECIMAL(5,1) DEFAULT NULL COMMENT '体重(kg)',
    gender TINYINT DEFAULT 0 COMMENT '0未知 1男 2女',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- 2. Movement library
CREATE TABLE IF NOT EXISTS coach_movement (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL COMMENT '动作名称',
    category VARCHAR(50) NOT NULL COMMENT '分类(上肢/下肢/核心)',
    UNIQUE KEY uk_name (name),
    description TEXT COMMENT '动作描述',
    standard_angles JSON COMMENT '标准角度配置',
    tips JSON COMMENT '纠错文案配置',
    image_url VARCHAR(255) DEFAULT '' COMMENT '示范图片',
    video_url VARCHAR(255) DEFAULT '' COMMENT '示范视频',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='动作库';

-- 3. Training session
CREATE TABLE IF NOT EXISTS coach_training_session (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL COMMENT '用户ID',
    movement_id BIGINT NOT NULL COMMENT '动作ID',
    score INT DEFAULT 0 COMMENT '综合评分(0-100)',
    duration_seconds INT DEFAULT 0 COMMENT '训练时长(秒)',
    rep_count INT DEFAULT 0 COMMENT '完成次数',
    error_summary JSON COMMENT '错误汇总JSON',
    avg_angles JSON COMMENT '平均角度JSON',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_user_id (user_id),
    INDEX idx_user_movement (user_id, movement_id),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='训练会话';

-- 4. Frame data (optional, mainly store error frames)
CREATE TABLE IF NOT EXISTS coach_frame_data (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    session_id BIGINT NOT NULL COMMENT '训练会话ID',
    frame_index INT NOT NULL COMMENT '帧序号',
    joint_data JSON NOT NULL COMMENT '33个关节点坐标JSON',
    is_error_frame TINYINT DEFAULT 0 COMMENT '是否错误帧',
    error_type VARCHAR(50) DEFAULT '' COMMENT '错误类型',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_session_id (session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='关键帧数据';

-- 5. Angle calculation results
CREATE TABLE IF NOT EXISTS coach_angle_result (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    session_id BIGINT NOT NULL COMMENT '训练会话ID',
    frame_index INT NOT NULL COMMENT '帧序号',
    joint_name VARCHAR(50) NOT NULL COMMENT '关节名称',
    angle_value DECIMAL(6,2) NOT NULL COMMENT '角度值',
    angle_status VARCHAR(10) DEFAULT 'NORMAL' COMMENT 'NORMAL/WARN/ERROR',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_session_id (session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角度计算结果';

-- 6. User achievements
CREATE TABLE IF NOT EXISTS coach_achievement (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL COMMENT '用户ID',
    achievement_type VARCHAR(50) NOT NULL COMMENT '成就类型',
    unlocked_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '解锁时间',
    UNIQUE KEY uk_user_achievement (user_id, achievement_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户成就';

-- Insert default movements (idempotent: skips if data already exists)

-- Individual INSERT statements for reliability
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('深蹲','下肢','双脚与肩同宽，缓慢下蹲至大腿与地面平行，保持腰背挺直。','{"leftKnee": {"min": 80, "max": 100, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}, "rightKnee": {"min": 80, "max": 100, "jointChain": ["rightHip", "rightKnee", "rightAnkle"]}, "leftHip": {"min": 70, "max": 100, "jointChain": ["leftShoulder", "leftHip", "leftKnee"]}, "rightHip": {"min": 70, "max": 100, "jointChain": ["rightShoulder", "rightHip", "rightKnee"]}, "backAngle": {"min": 60, "max": 90, "jointChain": ["leftShoulder", "leftHip", "leftAnkle"]}, "leftKneeOverToe": {"min": 0, "max": 3, "jointChain": ["leftKnee", "leftAnkle"]}, "rightKneeOverToe": {"min": 0, "max": 3, "jointChain": ["rightKnee", "rightAnkle"]}}','{"kneeOverToe": "重心后移膝盖不要超过脚尖", "kneeValgus": "膝盖不要内扣", "backRound": "挺直腰背不要弓背", "tooDeep": "下蹲过深", "tooShallow": "再蹲低一点", "leanForward": "上身不要太前倾"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('俯卧撑','上肢','双手略宽于肩，身体呈一条直线，屈肘下放至胸部接近地面。','{"leftElbow": {"min": 70, "max": 100, "jointChain": ["leftShoulder", "leftElbow", "leftWrist"]}, "rightElbow": {"min": 70, "max": 100, "jointChain": ["rightShoulder", "rightElbow", "rightWrist"]}, "bodyLine": {"min": 170, "max": 180, "jointChain": ["leftShoulder", "leftHip", "leftAnkle"]}, "leftShoulderAbduction": {"min": 0, "max": 45, "jointChain": ["leftHip", "leftShoulder", "leftElbow"]}, "rightShoulderAbduction": {"min": 0, "max": 45, "jointChain": ["rightHip", "rightShoulder", "rightElbow"]}}','{"elbowFlare": "手肘贴近身体", "hipSag": "收紧核心臀部不要下沉", "hipPike": "身体保持直线", "halfRep": "下放到胸部贴近地面", "headDrop": "保持颈部中立"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('平板支撑','核心','双肘撑地与肩同宽，脚尖着地，身体保持一条直线。','{"bodyLine": {"min": 170, "max": 180, "jointChain": ["leftShoulder", "leftHip", "leftAnkle"]}, "hipHeight": {"min": 0, "max": 15, "jointChain": ["leftShoulder", "leftHip"]}}','{"hipSag": "收紧核心", "hipPike": "臀部不要翘起", "headUp": "目视地面", "shoulderForward": "肩膀不要超过手肘", "breathHold": "保持均匀呼吸"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('弓步蹲','下肢','前脚向前跨一步，后腿膝盖接近地面，上身挺直。','{"frontKnee": {"min": 80, "max": 95, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}, "backKnee": {"min": 80, "max": 100, "jointChain": ["rightHip", "rightKnee", "rightAnkle"]}, "frontHip": {"min": 80, "max": 100, "jointChain": ["leftShoulder", "leftHip", "leftKnee"]}, "backAngle": {"min": 70, "max": 95, "jointChain": ["leftShoulder", "leftHip", "leftAnkle"]}}','{"frontKneeOverToe": "前腿膝盖不要超过脚尖", "backKneeLow": "后腿膝盖轻触地面", "leanForward": "上身挺直", "kneeValgus": "膝盖朝向脚尖"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('臀桥','下肢','仰卧屈膝，臀部发力抬起至身体成一条直线。','{"hipAngle": {"min": 160, "max": 180, "jointChain": ["leftShoulder", "leftHip", "leftKnee"]}, "kneeAngle": {"min": 60, "max": 90, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}}','{"lowHip": "臀部再抬高一点", "overExtend": "不要过度挺腰", "kneeOut": "膝盖与髋同宽"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('肩部推举','上肢','双手持重物于肩部高度，垂直向上推举至手臂伸直。','{"leftElbow": {"min": 160, "max": 180, "jointChain": ["leftShoulder", "leftElbow", "leftWrist"]}, "rightElbow": {"min": 160, "max": 180, "jointChain": ["rightShoulder", "rightElbow", "rightWrist"]}, "shoulderAngle": {"min": 140, "max": 180, "jointChain": ["leftHip", "leftShoulder", "leftElbow"]}}','{"halfRep": "手臂推到伸直", "leanBack": "核心收紧", "elbowFlare": "手肘内收"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('硬拉','下肢','双脚与髋同宽，屈髋向后，背部挺直拉起至站直。','{"backAngle": {"min": 50, "max": 80, "jointChain": ["leftShoulder", "leftHip", "leftAnkle"]}, "hipAngle": {"min": 60, "max": 100, "jointChain": ["leftShoulder", "leftHip", "leftKnee"]}, "kneeAngle": {"min": 130, "max": 170, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}}','{"backRound": "挺直腰背", "kneeLock": "膝盖微屈", "barFar": "杠铃贴身", "hipHigh": "先屈髋再屈膝"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('仰卧起坐','核心','仰卧屈膝，腹肌发力卷起上背部。','{"trunkAngle": {"min": 30, "max": 60, "jointChain": ["leftHip", "leftShoulder", "leftKnee"]}, "kneeAngle": {"min": 60, "max": 90, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}}','{"neckPull": "不要用手拉头部", "fullDown": "下落完全躺平", "hipLift": "臀部贴地"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('二头弯举','上肢','上臂贴紧身体，以肘为轴弯举，顶峰收缩后缓慢下放。','{"leftElbow": {"min": 30, "max": 50, "jointChain": ["leftShoulder", "leftElbow", "leftWrist"]}, "rightElbow": {"min": 30, "max": 50, "jointChain": ["rightShoulder", "rightElbow", "rightWrist"]}}','{"swing": "上臂保持不动", "halfRep": "全程控制", "wristBend": "手腕保持中立"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('高抬腿','下肢','原地跑步，大腿交替抬高至与地面平行。','{"leftHip": {"min": 70, "max": 100, "jointChain": ["leftShoulder", "leftHip", "leftKnee"]}, "rightHip": {"min": 70, "max": 100, "jointChain": ["rightShoulder", "rightHip", "rightKnee"]}, "leftKnee": {"min": 80, "max": 100, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}, "rightKnee": {"min": 80, "max": 100, "jointChain": ["rightHip", "rightKnee", "rightAnkle"]}}','{"kneeLow": "大腿抬至与地面平行", "leanBack": "身体挺直", "landHard": "前脚掌着地"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('靠墙静蹲','下肢','背靠墙壁，大腿与地面平行保持静止。','{"leftKnee": {"min": 85, "max": 100, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}, "rightKnee": {"min": 85, "max": 100, "jointChain": ["rightHip", "rightKnee", "rightAnkle"]}, "backAngle": {"min": 85, "max": 95, "jointChain": ["leftShoulder", "leftHip", "leftAnkle"]}}','{"tooDeep": "大腿与地面平行即可", "backOff": "背部贴紧墙面", "kneeForward": "膝盖不要超过脚尖"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('相扑深蹲','下肢','双脚宽于肩，脚尖45度朝外，屈髋屈膝下蹲。','{"leftKnee": {"min": 80, "max": 100, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}, "rightKnee": {"min": 80, "max": 100, "jointChain": ["rightHip", "rightKnee", "rightAnkle"]}, "leftHip": {"min": 60, "max": 90, "jointChain": ["leftShoulder", "leftHip", "leftKnee"]}, "rightHip": {"min": 60, "max": 90, "jointChain": ["rightShoulder", "rightHip", "rightKnee"]}}','{"kneeValgus": "膝盖朝脚尖方向打开", "backRound": "保持挺胸", "tooShallow": "下蹲至大腿与地面平行"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('保加利亚分腿蹲','下肢','后脚搭于凳沿，前腿屈膝下蹲至大腿与地面平行。','{"frontKnee": {"min": 80, "max": 95, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}, "frontHip": {"min": 70, "max": 95, "jointChain": ["leftShoulder", "leftHip", "leftKnee"]}, "backAngle": {"min": 70, "max": 95, "jointChain": ["leftShoulder", "leftHip", "leftAnkle"]}}','{"frontKneeOverToe": "前腿膝盖不要超过脚尖", "leanForward": "上身挺直", "kneeValgus": "膝盖朝前"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('侧弓步','下肢','向一侧跨步，屈膝下蹲，另一腿保持伸直。','{"bentKnee": {"min": 80, "max": 100, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}, "straightKnee": {"min": 150, "max": 180, "jointChain": ["rightHip", "rightKnee", "rightAnkle"]}, "backAngle": {"min": 70, "max": 95, "jointChain": ["leftShoulder", "leftHip", "leftAnkle"]}}','{"kneeOverToe": "屈膝腿膝盖不要超过脚尖", "straightLeg": "另一腿保持伸直", "leanForward": "上身挺直"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('小腿提踵','下肢','单脚站立，提踵至最高点，缓慢下落。','{"ankleAngle": {"min": 30, "max": 60, "jointChain": ["leftKnee", "leftAnkle", "leftWrist"]}, "kneeAngle": {"min": 170, "max": 180, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}}','{"halfRep": "提踵至最高", "tooFast": "动作缓慢控制", "kneeBend": "膝盖微屈"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('早安式体前屈','下肢','屈髋向后，上身向前倾，背部挺直，杠铃置于颈后。','{"backAngle": {"min": 50, "max": 80, "jointChain": ["leftShoulder", "leftHip", "leftAnkle"]}, "hipAngle": {"min": 50, "max": 80, "jointChain": ["leftShoulder", "leftHip", "leftKnee"]}, "kneeAngle": {"min": 150, "max": 170, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}}','{"backRound": "背部挺直不要弓背", "kneeBend": "膝盖微屈", "hipBack": "臀部向后推出"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('跳跃深蹲','下肢','深蹲后爆发力跳起，落地缓冲回到蹲位。','{"leftKnee": {"min": 80, "max": 100, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}, "rightKnee": {"min": 80, "max": 100, "jointChain": ["rightHip", "rightKnee", "rightAnkle"]}, "leftHip": {"min": 70, "max": 100, "jointChain": ["leftShoulder", "leftHip", "leftKnee"]}, "rightHip": {"min": 70, "max": 100, "jointChain": ["rightShoulder", "rightHip", "rightKnee"]}}','{"landSoft": "落地轻盈缓冲", "kneeValgus": "膝盖不要内扣", "backRound": "挺胸收腹"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('钻石俯卧撑','上肢','双手拇指和食指相触形成钻石形，屈肘下放。','{"leftElbow": {"min": 70, "max": 100, "jointChain": ["leftShoulder", "leftElbow", "leftWrist"]}, "rightElbow": {"min": 70, "max": 100, "jointChain": ["rightShoulder", "rightElbow", "rightWrist"]}, "bodyLine": {"min": 170, "max": 180, "jointChain": ["leftShoulder", "leftHip", "leftAnkle"]}}','{"elbowFlare": "手肘贴近身体", "halfRep": "胸部贴近手背", "hipSag": "身体保持直线"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('宽距俯卧撑','上肢','双手宽于肩1.5倍，主要刺激胸肌外侧。','{"leftElbow": {"min": 70, "max": 100, "jointChain": ["leftShoulder", "leftElbow", "leftWrist"]}, "rightElbow": {"min": 70, "max": 100, "jointChain": ["rightShoulder", "rightElbow", "rightWrist"]}, "bodyLine": {"min": 170, "max": 180, "jointChain": ["leftShoulder", "leftHip", "leftAnkle"]}, "leftShoulderAbduction": {"min": 0, "max": 50, "jointChain": ["leftHip", "leftShoulder", "leftElbow"]}, "rightShoulderAbduction": {"min": 0, "max": 50, "jointChain": ["rightHip", "rightShoulder", "rightElbow"]}}','{"hipSag": "身体保持直线", "halfRep": "下放至胸部接近地面", "elbowTooWide": "手肘角度适中"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('三头臂屈伸','上肢','双手撑于椅沿，屈肘下沉身体，三头肌发力推起。','{"leftElbow": {"min": 80, "max": 100, "jointChain": ["leftShoulder", "leftElbow", "leftWrist"]}, "rightElbow": {"min": 80, "max": 100, "jointChain": ["rightShoulder", "rightElbow", "rightWrist"]}}','{"elbowFlare": "手肘朝向正后方", "halfRep": "下沉至肘关节90度", "shoulderDown": "肩膀下沉"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('侧平举','上肢','双手持轻重量，向两侧平举至肩高，缓慢下放。','{"leftElbow": {"min": 150, "max": 180, "jointChain": ["leftShoulder", "leftElbow", "leftWrist"]}, "rightElbow": {"min": 150, "max": 180, "jointChain": ["rightShoulder", "rightElbow", "rightWrist"]}, "shoulderAngle": {"min": 70, "max": 100, "jointChain": ["leftHip", "leftShoulder", "leftElbow"]}}','{"swing": "不要摆动借力", "elbowBend": "手肘微屈", "tooHigh": "平举至肩高即可"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('前平举','上肢','双手持轻重量，向前平举至肩高，缓慢下放。','{"leftElbow": {"min": 150, "max": 180, "jointChain": ["leftShoulder", "leftElbow", "leftWrist"]}, "rightElbow": {"min": 150, "max": 180, "jointChain": ["rightShoulder", "rightElbow", "rightWrist"]}, "shoulderAngle": {"min": 70, "max": 100, "jointChain": ["leftHip", "leftShoulder", "leftElbow"]}}','{"swing": "不要摆动借力", "elbowBend": "手肘微屈", "leanBack": "身体不要后仰"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('跪姿俯卧撑','上肢','双膝着地，身体呈直线，屈肘下放至胸部接近地面。','{"leftElbow": {"min": 70, "max": 100, "jointChain": ["leftShoulder", "leftElbow", "leftWrist"]}, "rightElbow": {"min": 70, "max": 100, "jointChain": ["rightShoulder", "rightElbow", "rightWrist"]}, "bodyLine": {"min": 170, "max": 180, "jointChain": ["leftShoulder", "leftHip", "leftKnee"]}}','{"hipSag": "身体保持直线", "halfRep": "下放至胸部接近地面", "elbowFlare": "手肘贴近身体"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('上斜俯卧撑','上肢','双手撑于桌面或凳沿，身体倾斜，屈肘下放。','{"leftElbow": {"min": 70, "max": 100, "jointChain": ["leftShoulder", "leftElbow", "leftWrist"]}, "rightElbow": {"min": 70, "max": 100, "jointChain": ["rightShoulder", "rightElbow", "rightWrist"]}, "bodyLine": {"min": 170, "max": 180, "jointChain": ["leftShoulder", "leftHip", "leftAnkle"]}}','{"hipSag": "身体保持直线", "halfRep": "胸部贴近桌面", "elbowFlare": "手肘贴近身体"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('俄罗斯转体','核心','坐姿屈膝，双脚离地，双手合十左右转体。','{"trunkAngle": {"min": 30, "max": 60, "jointChain": ["leftShoulder", "leftHip", "rightShoulder"]}}','{"smallRange": "转体幅度要够大", "legDrop": "双腿保持稳定", "roundBack": "挺胸收腹"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('死虫式','核心','仰卧，对侧手脚交替伸展，核心收紧控制。','{"leftHip": {"min": 80, "max": 110, "jointChain": ["leftShoulder", "leftHip", "leftKnee"]}, "rightHip": {"min": 80, "max": 110, "jointChain": ["rightShoulder", "rightHip", "rightKnee"]}, "leftKnee": {"min": 80, "max": 100, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}, "rightKnee": {"min": 80, "max": 100, "jointChain": ["rightHip", "rightKnee", "rightAnkle"]}}','{"backArch": "下背部贴地", "fastMove": "动作缓慢控制", "breathHold": "配合呼吸"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('鸟狗式','核心','四足跪姿，对侧手脚同时伸展，保持身体稳定。','{"bodyLine": {"min": 170, "max": 180, "jointChain": ["leftShoulder", "leftHip", "leftAnkle"]}, "leftHip": {"min": 70, "max": 100, "jointChain": ["leftShoulder", "leftHip", "leftKnee"]}, "rightHip": {"min": 70, "max": 100, "jointChain": ["rightShoulder", "rightHip", "rightKnee"]}}','{"hipRotate": "骨盆不要旋转", "backArch": "核心收紧", "headUp": "颈部中立"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('侧平板','核心','单肘撑地，身体侧向呈一条直线，核心收紧保持。','{"bodyLine": {"min": 170, "max": 180, "jointChain": ["leftShoulder", "leftHip", "leftAnkle"]}}','{"hipSag": "身体保持直线", "shoulderStack": "肩肘垂直", "headUp": "颈部中立"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('登山者','核心','俯卧撑姿势，交替提膝向胸，保持核心收紧。','{"leftHip": {"min": 60, "max": 90, "jointChain": ["leftShoulder", "leftHip", "leftKnee"]}, "rightHip": {"min": 60, "max": 90, "jointChain": ["rightShoulder", "rightHip", "rightKnee"]}, "leftKnee": {"min": 70, "max": 100, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}, "rightKnee": {"min": 70, "max": 100, "jointChain": ["rightHip", "rightKnee", "rightAnkle"]}}','{"hipHigh": "臀部不要抬高", "fastRhythm": "保持匀速", "halfKnee": "膝盖尽量靠近胸部"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('V字卷腹','核心','仰卧，同时抬起上身和双腿，双手触碰脚尖。','{"trunkAngle": {"min": 30, "max": 60, "jointChain": ["leftHip", "leftShoulder", "leftKnee"]}, "kneeAngle": {"min": 150, "max": 170, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}}','{"halfRep": "充分卷起", "swing": "腹肌发力不借力", "legBend": "腿尽量伸直"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('波比跳','全身','深蹲接俯卧撑接跳跃，连续完成，全身协调发力。','{"leftKnee": {"min": 80, "max": 100, "jointChain": ["leftHip", "leftKnee", "leftAnkle"]}, "rightKnee": {"min": 80, "max": 100, "jointChain": ["rightHip", "rightKnee", "rightAnkle"]}, "leftElbow": {"min": 70, "max": 100, "jointChain": ["leftShoulder", "leftElbow", "leftWrist"]}, "rightElbow": {"min": 70, "max": 100, "jointChain": ["rightShoulder", "rightElbow", "rightWrist"]}}','{"hipSag": "俯卧时身体直线", "halfSquat": "深蹲到位", "landSoft": "跳跃落地缓冲"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('开合跳','全身','并腿站立，跳起分腿，同时双手在头顶击掌，再跳回。','{"leftHip": {"min": 40, "max": 70, "jointChain": ["leftShoulder", "leftHip", "leftKnee"]}, "rightHip": {"min": 40, "max": 70, "jointChain": ["rightShoulder", "rightHip", "rightKnee"]}, "leftElbow": {"min": 140, "max": 180, "jointChain": ["leftShoulder", "leftElbow", "leftWrist"]}, "rightElbow": {"min": 140, "max": 180, "jointChain": ["rightShoulder", "rightElbow", "rightWrist"]}}','{"smallJump": "跳起幅度要大", "armDown": "手臂举过头顶", "landSoft": "落地缓冲"}');;
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('单腿深蹲','下肢','单腿站立，另一腿前伸，缓慢下蹲至支撑大腿与地面平行。','{"leftKnee":{"min":80,"max":100,"jointChain":["leftHip","leftKnee","leftAnkle"]},"leftHip":{"min":70,"max":100,"jointChain":["leftShoulder","leftHip","leftKnee"]},"backAngle":{"min":60,"max":90,"jointChain":["leftShoulder","leftHip","leftAnkle"]}}','{"kneeValgus":"膝盖朝前不要内扣","backRound":"挺直腰背","tooDeep":"控制深度"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('后撤步弓步','下肢','向后跨一步，双腿屈膝下蹲，前腿发力回到起始位。','{"frontKnee":{"min":80,"max":100,"jointChain":["leftHip","leftKnee","leftAnkle"]},"backKnee":{"min":80,"max":100,"jointChain":["rightHip","rightKnee","rightAnkle"]},"backAngle":{"min":70,"max":95,"jointChain":["leftShoulder","leftHip","leftAnkle"]}}','{"kneeOverToe":"前膝不要超过脚尖","leanForward":"上身挺直","balance":"保持平衡"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('交替弓步跳','下肢','弓步姿势，跳起空中交换双腿，落地缓冲。','{"frontKnee":{"min":80,"max":100,"jointChain":["leftHip","leftKnee","leftAnkle"]},"backKnee":{"min":80,"max":100,"jointChain":["rightHip","rightKnee","rightAnkle"]}}','{"landSoft":"落地缓冲","kneeValgus":"膝盖朝前","balance":"控制平衡"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('蛙跳','下肢','深蹲位，双手背后，向前跳跃，落地缓冲。','{"leftKnee":{"min":80,"max":100,"jointChain":["leftHip","leftKnee","leftAnkle"]},"rightKnee":{"min":80,"max":100,"jointChain":["rightHip","rightKnee","rightAnkle"]},"leftHip":{"min":70,"max":100,"jointChain":["leftShoulder","leftHip","leftKnee"]}}','{"landSoft":"落地轻盈","backRound":"挺胸","kneeValgus":"膝盖朝前"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('蟹步走','下肢','四肢撑地，腹部朝上，横向移动。','{"leftElbow":{"min":140,"max":180,"jointChain":["leftShoulder","leftElbow","leftWrist"]},"rightElbow":{"min":140,"max":180,"jointChain":["rightShoulder","rightElbow","rightWrist"]},"leftHip":{"min":140,"max":180,"jointChain":["leftShoulder","leftHip","leftKnee"]}}','{"hipSag":"臀部不要下沉","slowMove":"控制速度","core":"核心收紧"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('引体向上','上肢','双手正握单杠，背阔肌发力将身体拉起至下巴过杠。','{"leftElbow":{"min":30,"max":50,"jointChain":["leftShoulder","leftElbow","leftWrist"]},"rightElbow":{"min":30,"max":50,"jointChain":["rightShoulder","rightElbow","rightWrist"]},"shoulderAngle":{"min":140,"max":180,"jointChain":["leftHip","leftShoulder","leftElbow"]}}','{"swing":"不要摆动借力","fullROM":"下巴过杠","halfRep":"手臂下放至伸直"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('俯身划船','上肢','屈髋俯身，背部挺直，将重物沿大腿拉向腹部。','{"leftElbow":{"min":50,"max":80,"jointChain":["leftShoulder","leftElbow","leftWrist"]},"rightElbow":{"min":50,"max":80,"jointChain":["rightShoulder","rightElbow","rightWrist"]},"backAngle":{"min":50,"max":80,"jointChain":["leftShoulder","leftHip","leftAnkle"]}}','{"backRound":"背部挺直","swing":"控制速度","elbowIn":"手肘贴近身体"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('蜘蛛人俯卧撑','上肢','俯卧撑位，屈肘时一侧膝盖向同侧手肘靠近。','{"leftElbow":{"min":70,"max":100,"jointChain":["leftShoulder","leftElbow","leftWrist"]},"rightElbow":{"min":70,"max":100,"jointChain":["rightShoulder","rightElbow","rightWrist"]},"leftHip":{"min":60,"max":90,"jointChain":["leftShoulder","leftHip","leftKnee"]}}','{"hipSag":"身体保持直线","kneeToElbow":"膝盖靠近手肘","slowMove":"控制节奏"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('仰卧抬腿','核心','仰卧，双腿并拢伸直，腹肌发力抬起至垂直地面。','{"leftHip":{"min":70,"max":100,"jointChain":["leftShoulder","leftHip","leftKnee"]},"rightHip":{"min":70,"max":100,"jointChain":["rightShoulder","rightHip","rightKnee"]},"kneeAngle":{"min":150,"max":180,"jointChain":["leftHip","leftKnee","leftAnkle"]}}','{"swing":"腹肌发力不借力","legBend":"腿尽量伸直","backArch":"下背贴地"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('剪刀腿','核心','仰卧，双腿伸直交替上下交叉摆动。','{"leftHip":{"min":60,"max":90,"jointChain":["leftShoulder","leftHip","leftKnee"]},"rightHip":{"min":60,"max":90,"jointChain":["rightShoulder","rightHip","rightKnee"]}}','{"backArch":"下背贴地","fastMove":"控制速度","legStraight":"双腿伸直"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('交替触踝','核心','仰卧屈膝，上身微抬，左右交替触摸脚踝。','{"trunkAngle":{"min":20,"max":50,"jointChain":["leftHip","leftShoulder","leftKnee"]}}','{"neckPull":"颈部放松","sideBend":"侧腹发力","breath":"配合呼吸"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('平板交替抬手','核心','平板支撑位，交替向前伸直手臂，保持身体稳定。','{"bodyLine":{"min":170,"max":180,"jointChain":["leftShoulder","leftHip","leftAnkle"]},"leftElbow":{"min":160,"max":180,"jointChain":["leftShoulder","leftElbow","leftWrist"]}}','{"hipRotate":"骨盆保持稳定","slowMove":"控制速度","core":"核心收紧"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('猫牛式','拉伸','四足跪姿，吸气时弓背低头，呼气时塌腰抬头。','{"backAngle":{"min":40,"max":80,"jointChain":["leftShoulder","leftHip","leftAnkle"]},"trunkAngle":{"min":40,"max":80,"jointChain":["leftHip","leftShoulder","leftKnee"]}}','{"slowMove":"配合呼吸缓慢移动","fullROM":"完整活动范围","relax":"肩颈放松"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('下犬式','拉伸','从平板支撑位推臀向上，身体呈倒V形，脚跟下压。','{"bodyLine":{"min":130,"max":160,"jointChain":["leftShoulder","leftHip","leftAnkle"]},"hipAngle":{"min":80,"max":110,"jointChain":["leftShoulder","leftHip","leftKnee"]}}','{"heelsDown":"脚跟向地面下压","backStraight":"背部挺直","headRelax":"头部放松"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('婴儿式','拉伸','跪坐，上身前倾，额头贴地，双臂前伸或放于体侧。','{"hipAngle":{"min":30,"max":60,"jointChain":["leftShoulder","leftHip","leftKnee"]},"kneeAngle":{"min":60,"max":90,"jointChain":["leftHip","leftKnee","leftAnkle"]}}','{"relax":"全身放松","breath":"深呼吸","hipsBack":"臀部坐向脚跟"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('肩部拉伸','拉伸','一侧手臂横过胸前，另一手辅助拉伸。','{"leftElbow":{"min":150,"max":180,"jointChain":["leftShoulder","leftElbow","leftWrist"]},"shoulderAngle":{"min":70,"max":100,"jointChain":["leftHip","leftShoulder","leftElbow"]}}','{"gentle":"轻柔拉伸","noPain":"不要拉到疼痛","hold":"保持15-30秒"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('站立体前屈','拉伸','站立位，缓慢向前弯曲，双手触地或小腿。','{"backAngle":{"min":30,"max":60,"jointChain":["leftShoulder","leftHip","leftAnkle"]},"kneeAngle":{"min":150,"max":180,"jointChain":["leftHip","leftKnee","leftAnkle"]}}','{"kneeBend":"膝盖微屈","slowMove":"缓慢下弯","relax":"头部放松"}');
INSERT IGNORE INTO coach_movement (name, category, description, standard_angles, tips) VALUES ('上犬式','拉伸','俯卧，双手推地，上身抬起，大腿离地。','{"backAngle":{"min":120,"max":150,"jointChain":["leftShoulder","leftHip","leftAnkle"]},"leftElbow":{"min":150,"max":180,"jointChain":["leftShoulder","leftElbow","leftWrist"]}}','{"shouldersDown":"肩膀下沉","chestOpen":"胸腔打开","legsActive":"大腿收紧"}');;
